### ISSUE TITLE
Add datacard Mexico

### ISSUE THREAD

**Issue by oumniaennaji** [BigDataWUR/AgML-crop-yield-forecasting#111]

**Comment by oumniaennaji** [comment]
[mexico data card.pdf](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/files/14824700/mexico.data.card.pdf)
 
@krsnapaudel : I can add this one that is ready until we finalize the rest with Inti. Kindly check it. Thanks

**Comment by krsnapaudel** [comment]
@oumniaennaji : Please check contributing guide under data preparation.

**Comment by krsnapaudel** [comment]
Merged with #138
