### ISSUE TITLE
Data card for soil moisture

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-crop-yield-forecasting#123]
See data card template and examples under `data_preparation`.

**Comment by ritviksahajpal** [comment]
# Soil Moisture

## Global Soil Moisture Data from GLDAS

## Link
https://ldas.gsfc.nasa.gov/gldas/model-output

## Publisher
NASA

## Dataset owner
NASA

## Data card author
Ritvik Sahajpal

## Dataset overview
GLDAS provides information on root zone soil moisture data 

Example for crop yield, area and production statistics

**Crops**: NA

**Variables** [unit]: kg/m^2

**Temporal coverage**: 2003 - 2023

**Temporal resolution**: 1 day

**Spatial resolution**: 0.25 deg x 0.25 deg

## Provenance 
GLDAS 2.2

# License 
Available for public use at https://disc.gsfc.nasa.gov/datasets?keywords=GLDAS

## How to cite
Rodell, M., P.R. Houser, U. Jambor, J. Gottschalck, K. Mitchell, C.-J. Meng, K. Arsenault, B. Cosgrove, J. Radakovich, M. Bosilovich, J.K. Entin, J.P. Walker, D. Lohmann, and D. Toll, The Global Land Data Assimilation System, Bull. Amer. Meteor. Soc., 85(3), 381-394, 2004.

## References
Rodell, M., P.R. Houser, U. Jambor, J. Gottschalck, K. Mitchell, C.-J. Meng, K. Arsenault, B. Cosgrove, J. Radakovich, M. Bosilovich, J.K. Entin, J.P. Walker, D. Lohmann, and D. Toll, The Global Land Data Assimilation System, Bull. Amer. Meteor. Soc., 85(3), 381-394, 2004.

**Comment by krsnapaudel** [comment]
@ritviksahajpal : I will create a pull request. Please check and suggest updates. Mainly a short description and how the data is produced. Thanks.
