### ISSUE TITLE
outline file for data sources selection and justification

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-crop-yield-forecasting#151]
Create `DATA-SOURCES-SELECTION.md` under `data_preparation`.

**Comment by krsnapaudel** [comment]
SOILGRIDS vs Soil WISE: @ajwdewit

**Comment by ajwdewit** [comment]
- agronomic interpretation is easier for WISE compared to SoilGrids
- soilgrids did not provide soil rootable depth and water holding capacity (this may have changed recently)
- WISE is based on soil maps whose properties are estimated by expert knowledge collected over the years. In NL we see that the performance of BOFEK (similar to WISE) is still considerably better than SoilGrids for NL.
