### ISSUE TITLE
Review of crop statistics for Mali

### ISSUE THREAD

**Issue by gnodnooh** [BigDataWUR/AgML-crop-yield-forecasting#174]
I'm raising the following points after quick-checking the Mali data:

- This crop statistics report covers the southern parts of Mali, which are the major producing regions, rather than the entire country.

- It might be helpful to explain the contents of each CSV file. The “maize_aggregated_yield_stats.csv” file contains general statistics about the data, not the data itself.

- While crop statistics data has "adm3_pcode" column, the shapefile does not have any relevant ID column. It only includes “CMDTsector” and “CMDYsecto2”.

- For the file “maize_production_area_aggre_yield_data.csv”:
  - How have production and area been measured? Can we say these values represent the total production and area within a unit, or are they the total “surveyed” amounts?
  - Some rows have zero or missing values for all indicators (production, area, and yield).

**Comment by krsnapaudel** [comment]
Thanks @gnodnooh. @janet6868 Please address the above comments in data card or data preparation notebook. Thanks.

**Comment by janet6868** [comment]
@gnodnooh 
1. I have combined the shapefiles with the data into a single shapefile. This includes the production in tons, yield in mt/ha, planted area in hectares, and geometries.
2.  The derived yield statistics have been excluded since they can be calculated from the original data. 
3.

**Comment by janet6868** [comment]
![image](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/46169449/6e46cdc4-f47f-48e9-aeb6-5ead6c078cc3)
The extent does not mean it is just one polygon.
756 represents the sectors in the data one large polygon (MultiPolygon)

**Comment by janet6868** [comment]
when you check the attribute table:
![image](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/46169449/c19f8554-36b7-4383-88e7-a426e102ed68)

**Comment by janet6868** [comment]
@gnodnooh please let me know if you would like me to share it as geojson.

**Comment by gnodnooh** [comment]
Thanks, @janet6868. Your comments are very helpful. My point is that we may only need a single feature or polygon (row) for each adm_id for the further process of aggregating climate data. I see that each adm_id has 28 duplicated polygons (rows). It’s not a significant issue, but it would just be a preference 👌

**Comment by janet6868** [comment]
Hello @gnodnooh
I get your point.
It is because we have 28 years for each adm_id (1990-2017). Let me know if this info helps.
Thanks

**Comment by janet6868** [comment]
@gnodnooh 
![image](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/46169449/734adaef-6fee-46fe-85a2-d02d03714e3c)
Here is one challenge of using a single feature per `adm_id`. I am working with third-level administrative boundaries, where each level can contain two or more sectors. Removing duplicates could result in losing important features, as illustrated by the purple-colored features that would be dropped. To address this, I will append the sector's unique ID to the administrative ID, ensuring each of the 27 features remains unique. I will update you once this is completed.

**Comment by janet6868** [comment]
![image](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/46169449/f079577e-ecab-4e80-9f53-f1babd75e062)
@gnodnooh its done.
Kindly it out.

**Comment by gnodnooh** [comment]
Looks good to me. Thanks for your work!
