### ISSUE TITLE
expected data format

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-crop-yield-forecasting#65]
Add a document describing expected data format.

**Comment by CarlaLimone** [comment]
Can we remove the variable 'source' in the data format for the yield data? This information is already in the data card. We could replace it with 'version' and keep this variable optional - just in case that we onboard a data set that is still in preparation and not yet in final state.
Can we provide standard names for the crops we want to model? e.g. 'wheat, grain_maize, rice' (I would not use the term 'winter' for 'winter wheat' as some world regions do not use this term to characterize their seasons.
