### ISSUE TITLE
a map showing spatial coverage by crop

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-crop-yield-forecasting#77]
It would be useful to visualize the countries covered by our data by crop. @oumniaennaji Could you take the lead and ask for support if needed? Thanks.

**Comment by oumniaennaji** [comment]
Indeed, that is part of what I had planned for the milestones. Thank you @krsnapaudel.

**Comment by oumniaennaji** [comment]
<img width="807" alt="All_datasets" src="https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/73598833/3162ccf7-1304-46b9-8224-ff8b2c7b5e26">

This map shows the general coverage of all the datasets I made similar for each crop but only the top three we are focusing on wheat, corn, and rice should I add the other crops ? @krsnapaudel what do you think ? Thanks.

**Comment by krsnapaudel** [comment]
@oumniaennaji : for now wheat (could be winter or spring) and grain maize would do. Could we start with the crop mask and label countries covered on top of it? That way we know our coverage relative to areas with the crop. Thanks.

**Comment by oumniaennaji** [comment]
@krsnapaudel: Sure! I will add the crop masks and country names then to the README. Thank you for you feedback.

**Comment by oumniaennaji** [comment]
![final_mapagml](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/73598833/895a7daa-3019-4aee-a0b9-b5866221b46a)
Hi @krsnapaudel I've  added the grain maize and wheat masks to the  map. However, the country labels appear visually cluttered, especially in Europe, even when using acronyms. Do you have any suggestions on how to improve the label readability before adding the maps to README? Thanks,

**Comment by krsnapaudel** [comment]
Hello @oumniaennaji, The labels are not as important. Please separate the two crops. Also I don't see the crop masks in the background. Thanks.
